version: "3.9"
services:
  mydb:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  free2move:
    image: free2move_image
    container_name: free2move_container
    volumes:
      - ./data/:/tmp/data/
    links:
      - mydb

volumes:
  db-data:
    driver: local
